### ISSUE TITLE
Save the panel position state

### ISSUE THREAD

**Issue by TimPietrusky** [vcync/modv-3#131]
It's already possible to change the position of every panel, but that is not saved anywhere. 

h2. Desired Behavior
I change the position of the panels and it gets stored, so I can restart modV and still have the same panel positions as before

**Comment by 2xAA** [comment]
This is possible with Golden Layout.

Info on this here:
https://github.com/emedware/vue-golden-layout#savingrestoring-states

**Comment by 2xAA** [comment]
I've got this working at a very basic level, though the module inspector (https://github.com/vcync/modv-3/blob/main/src/App.vue#L12) breaks the layout restoration.

Vue's component layout at the time the Golden Layout state is saved must match the saved state when mounting, otherwise an Error is thrown and the panel positions cannot be restored.

We now have two options:

1. We create a bespoke component for the module inspector which does not use Golden Layout
2. We prevent dynamic components being saved to the state by using `GoldenLayout. unminifyConfig` on the state object, then traverse and remove the panels we know will not be available on startup

I'm leaning towards 2 as having the module inspector using Golden Layout panels is really nice.

**Comment by 2xAA** [comment]
Approach 2 works, but if you move a panel out of the `dynamic-panel` Stack, the title is lost and we can't find all the panels to remove.

We could maybe use Golden Layout's componentState to mark panels we know will not be present when restoring the state.
